### ISSUE TITLE
RotaryEmbeddingLayer should support static_tables=False

### ISSUE THREAD

**Issue by stellaraccident** [nod-ai/sharktank#156]
Currently, if `static_tables=False` for the RotaryEmbeddingLayer, it emits ops that are not yet supported (namely torch.aten.polar). As such, hardcoding to `True` for the moment, which pre-initializes the table during init and is embedded into the mlir, making it much larger than needed. We should preserve the calculation explicitly and rely on the compiler to transform it to an initialization time step.

Repro Instructions:

Download mlir from here: https://sharkpublic.blob.core.windows.net/sharkpublic/sai/llama3_8b_compile_failure/model.mlir

`iree-compile model.mlir --iree-hal-target-backends="rocm" --iree-hip-target=gfx942  -o model.vmfb`

Failure log:
```
llama8b_f16_test.mlir:1114:12: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %384 = torch.operator "torch.aten.polar"(%383, %382) : (!torch.vtensor<[131072,64],f32>, !torch.vtensor<[131072,64],f32>) -> !torch.vtensor<[131072,64],complex<f32>>
           ^
llama8b_f16_test.mlir:1114:12: note: see current operation: %718 = "torch.operator"(%717, %716) <{name = "torch.aten.polar"}> : (!torch.vtensor<[131072,64],f32>, !torch.vtensor<[131072,64],f32>) -> !torch.vtensor<[131072,64],complex<f32>>
llama8b_f16_test.mlir:17750:12: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %832 = torch.operator "torch.aten.polar"(%831, %830) : (!torch.vtensor<[131072,64],f32>, !torch.vtensor<[131072,64],f32>) -> !torch.vtensor<[131072,64],complex<f32>>
           ^
llama8b_f16_test.mlir:17750:12: note: see current operation: %699 = "torch.operator"(%698, %697) <{name = "torch.aten.polar"}> : (!torch.vtensor<[131072,64],f32>, !torch.vtensor<[131072,64],f32>) -> !torch.vtensor<[131072,64],complex<f32>>
```

Looks like we need to implement the torch -> linalg lowering for torch.polar

With this fix, we can make the initialization of the rotary embedding table dynamic as well, dropping the mlir size from 137 mb -> 4 mb.

**Comment by vivekkhandelwal1** [comment]
Fixed by https://github.com/llvm/torch-mlir/pull/3671
