### ISSUE TITLE
transpose_rhs argument in matmul

### ISSUE THREAD

**Issue by sogartar** [nod-ai/sharktank#56]
What is the reason for having the `transpose_rhs` in the [matmul signature](https://github.com/nod-ai/sharktank/blob/b5d9add33bb6b594039fed043e8bb90d5a928007/sharktank/sharktank/ops/signatures.py#L246)? Is it to somehow aide the compiler to fuse the transpose? But it seems then we take the transpose (`rhs.T`) and do the matmul anyway. Can't we have the user do the transpose on the outside?

Should we remove this argument? Unless we have a good reason to keep it, I think it should be removed. Let's not complicate the signature.

If we need to keep it, its default value should be False, to match the signature of torch's matmul in the default case.

**Comment by sogartar** [comment]
@stellaraccident, what do you think?

**Comment by stellaraccident** [comment]
Almost all matmuls in any modern ml model are the transpose_rhs form, and frankly, I got tired of having the baseline thing be strangely transposed. I shouldn't have called this "matmul" though. 

There are many kernels, especially on the inference side, that are only defined for transpose_rhs, and it is useful to be able to specialize those without relying on fusion heuristics -- I'd go so far as to say that the absence of this one thing is a key factor in why torch isn't very good for inference out of the box. 

So, if I had to choose one, I would ignore defining specializations for plain matmul, as it rarely shows up on its own.

**Comment by stellaraccident** [comment]
I've since added the linear op: https://github.com/nod-ai/sharktank/blob/b5d9add33bb6b594039fed043e8bb90d5a928007/sharktank/sharktank/ops/signatures.py#L202

And was thinking of migrating all of the transpose_b matmul stuff to that, then switching the default or dropping the flag.

**Comment by sogartar** [comment]
I can migrate to the linear op. For matmul I will retain the flag but change its default.
I would also like to add the transpose method to the signatures. I want it for the sharded tensors. Maybe add the `T` property to the `InferenceTensor` to match torch and make model porting easier.

**Comment by sogartar** [comment]
Done with #60.
